"""Curated problem sets, grouped by skill / topic.

Each set is an ordered list of (frontend_id, slug, difficulty) tuples, roughly
ordered from fundamentals to hard. Difficulty is "E", "M" or "H" and is used
as an offline fallback; live data from LeetCode overrides it when available.

Selection criteria: the canonical problem for a technique, problems that show
up repeatedly in big-tech interviews (Blind 75 / NeetCode 150 / Grind 169 /
Top Interview 150 overlap), and problems that teach an important variant.
A few premium-only problems are included where they are the canonical example
(e.g. Meeting Rooms II); LeetCode marks them with a lock when listed.

Users can add their own sets in ~/.config/leetcode-cli/sets.json:

    {
      "my-weak-spots": {
        "description": "Things I keep failing",
        "problems": ["two-sum", 146, "lru-cache"]
      }
    }

Entries may be slugs or numeric frontend IDs (IDs are resolved online).
"""

from __future__ import annotations

import json
from pathlib import Path

from config import CONFIG_DIR

USER_SETS_FILE = CONFIG_DIR / "sets.json"

DIFF_WEIGHT = {"E": 1, "M": 2, "H": 3}
DIFF_NAME = {"E": "Easy", "M": "Medium", "H": "Hard"}

# ---------------------------------------------------------------------------
# Built-in sets
# ---------------------------------------------------------------------------

BUILTIN_SETS: dict[str, dict] = {
    # ------------------------------------------------------------------ core
    "arrays-hashing": {
        "description": "Arrays, hash maps, counting, in-place tricks",
        "problems": [
            (1, "two-sum", "E"),
            (217, "contains-duplicate", "E"),
            (242, "valid-anagram", "E"),
            (169, "majority-element", "E"),
            (448, "find-all-numbers-disappeared-in-an-array", "E"),
            (121, "best-time-to-buy-and-sell-stock", "E"),
            (49, "group-anagrams", "M"),
            (347, "top-k-frequent-elements", "M"),
            (238, "product-of-array-except-self", "M"),
            (128, "longest-consecutive-sequence", "M"),
            (36, "valid-sudoku", "M"),
            (53, "maximum-subarray", "M"),
            (560, "subarray-sum-equals-k", "M"),
            (56, "merge-intervals", "M"),
            (48, "rotate-image", "M"),
            (54, "spiral-matrix", "M"),
            (73, "set-matrix-zeroes", "M"),
            (380, "insert-delete-getrandom-o1", "M"),
            (271, "encode-and-decode-strings", "M"),
            (41, "first-missing-positive", "H"),
        ],
    },
    "two-pointers": {
        "description": "Opposite-end and fast/slow pointer patterns",
        "problems": [
            (125, "valid-palindrome", "E"),
            (344, "reverse-string", "E"),
            (26, "remove-duplicates-from-sorted-array", "E"),
            (283, "move-zeroes", "E"),
            (88, "merge-sorted-array", "E"),
            (977, "squares-of-a-sorted-array", "E"),
            (680, "valid-palindrome-ii", "E"),
            (167, "two-sum-ii-input-array-is-sorted", "M"),
            (15, "3sum", "M"),
            (16, "3sum-closest", "M"),
            (18, "4sum", "M"),
            (11, "container-with-most-water", "M"),
            (75, "sort-colors", "M"),
            (189, "rotate-array", "M"),
            (42, "trapping-rain-water", "H"),
        ],
    },
    "sliding-window": {
        "description": "Fixed and variable-size window over arrays and strings",
        "problems": [
            (643, "maximum-average-subarray-i", "E"),
            (121, "best-time-to-buy-and-sell-stock", "E"),
            (3, "longest-substring-without-repeating-characters", "M"),
            (209, "minimum-size-subarray-sum", "M"),
            (424, "longest-repeating-character-replacement", "M"),
            (567, "permutation-in-string", "M"),
            (438, "find-all-anagrams-in-a-string", "M"),
            (1004, "max-consecutive-ones-iii", "M"),
            (904, "fruit-into-baskets", "M"),
            (1493, "longest-subarray-of-1s-after-deleting-one-element", "M"),
            (1423, "maximum-points-you-can-obtain-from-cards", "M"),
            (930, "binary-subarrays-with-sum", "M"),
            (1438, "longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit", "M"),
            (76, "minimum-window-substring", "H"),
            (239, "sliding-window-maximum", "H"),
            (992, "subarrays-with-k-different-integers", "H"),
            (30, "substring-with-concatenation-of-all-words", "H"),
        ],
    },
    "prefix-sum": {
        "description": "Prefix sums, difference arrays, hashing of running totals",
        "problems": [
            (1480, "running-sum-of-1d-array", "E"),
            (724, "find-pivot-index", "E"),
            (303, "range-sum-query-immutable", "E"),
            (1732, "find-the-highest-altitude", "E"),
            (304, "range-sum-query-2d-immutable", "M"),
            (560, "subarray-sum-equals-k", "M"),
            (523, "continuous-subarray-sum", "M"),
            (525, "contiguous-array", "M"),
            (974, "subarray-sums-divisible-by-k", "M"),
            (1248, "count-number-of-nice-subarrays", "M"),
            (1109, "corporate-flight-bookings", "M"),
            (1094, "car-pooling", "M"),
            (528, "random-pick-with-weight", "M"),
            (1314, "matrix-block-sum", "M"),
            (2381, "shifting-letters-ii", "M"),
            (1074, "number-of-submatrices-that-sum-to-target", "H"),
            (862, "shortest-subarray-with-sum-at-least-k", "H"),
            (363, "max-sum-of-rectangle-no-larger-than-k", "H"),
        ],
    },
    "binary-search": {
        "description": "Classic, rotated arrays, and binary search on the answer",
        "problems": [
            (704, "binary-search", "E"),
            (35, "search-insert-position", "E"),
            (278, "first-bad-version", "E"),
            (69, "sqrtx", "E"),
            (74, "search-a-2d-matrix", "M"),
            (34, "find-first-and-last-position-of-element-in-sorted-array", "M"),
            (33, "search-in-rotated-sorted-array", "M"),
            (153, "find-minimum-in-rotated-sorted-array", "M"),
            (81, "search-in-rotated-sorted-array-ii", "M"),
            (162, "find-peak-element", "M"),
            (540, "single-element-in-a-sorted-array", "M"),
            (287, "find-the-duplicate-number", "M"),
            (240, "search-a-2d-matrix-ii", "M"),
            (658, "find-k-closest-elements", "M"),
            (875, "koko-eating-bananas", "M"),
            (1011, "capacity-to-ship-packages-within-d-days", "M"),
            (1283, "find-the-smallest-divisor-given-a-threshold", "M"),
            (981, "time-based-key-value-store", "M"),
            (410, "split-array-largest-sum", "H"),
            (4, "median-of-two-sorted-arrays", "H"),
        ],
    },
    "stack": {
        "description": "Stacks, monotonic stacks, expression parsing",
        "problems": [
            (20, "valid-parentheses", "E"),
            (155, "min-stack", "M"),
            (232, "implement-queue-using-stacks", "E"),
            (1047, "remove-all-adjacent-duplicates-in-string", "E"),
            (496, "next-greater-element-i", "E"),
            (150, "evaluate-reverse-polish-notation", "M"),
            (22, "generate-parentheses", "M"),
            (71, "simplify-path", "M"),
            (394, "decode-string", "M"),
            (739, "daily-temperatures", "M"),
            (503, "next-greater-element-ii", "M"),
            (853, "car-fleet", "M"),
            (735, "asteroid-collision", "M"),
            (402, "remove-k-digits", "M"),
            (316, "remove-duplicate-letters", "M"),
            (901, "online-stock-span", "M"),
            (456, "132-pattern", "M"),
            (227, "basic-calculator-ii", "M"),
            (907, "sum-of-subarray-minimums", "M"),
            (84, "largest-rectangle-in-histogram", "H"),
            (85, "maximal-rectangle", "H"),
            (224, "basic-calculator", "H"),
            (32, "longest-valid-parentheses", "H"),
        ],
    },
    "linked-list": {
        "description": "Pointer manipulation, cycles, merging, reordering",
        "problems": [
            (206, "reverse-linked-list", "E"),
            (21, "merge-two-sorted-lists", "E"),
            (141, "linked-list-cycle", "E"),
            (876, "middle-of-the-linked-list", "E"),
            (234, "palindrome-linked-list", "E"),
            (160, "intersection-of-two-linked-lists", "E"),
            (83, "remove-duplicates-from-sorted-list", "E"),
            (203, "remove-linked-list-elements", "E"),
            (2, "add-two-numbers", "M"),
            (19, "remove-nth-node-from-end-of-list", "M"),
            (142, "linked-list-cycle-ii", "M"),
            (143, "reorder-list", "M"),
            (138, "copy-list-with-random-pointer", "M"),
            (92, "reverse-linked-list-ii", "M"),
            (24, "swap-nodes-in-pairs", "M"),
            (82, "remove-duplicates-from-sorted-list-ii", "M"),
            (61, "rotate-list", "M"),
            (86, "partition-list", "M"),
            (328, "odd-even-linked-list", "M"),
            (148, "sort-list", "M"),
            (146, "lru-cache", "M"),
            (707, "design-linked-list", "M"),
            (25, "reverse-nodes-in-k-group", "H"),
            (23, "merge-k-sorted-lists", "H"),
        ],
    },
    # ----------------------------------------------------------------- trees
    "trees": {
        "description": "Binary tree traversal, recursion, construction, BST",
        "problems": [
            (226, "invert-binary-tree", "E"),
            (104, "maximum-depth-of-binary-tree", "E"),
            (100, "same-tree", "E"),
            (101, "symmetric-tree", "E"),
            (94, "binary-tree-inorder-traversal", "E"),
            (543, "diameter-of-binary-tree", "E"),
            (110, "balanced-binary-tree", "E"),
            (572, "subtree-of-another-tree", "E"),
            (112, "path-sum", "E"),
            (235, "lowest-common-ancestor-of-a-binary-search-tree", "M"),
            (102, "binary-tree-level-order-traversal", "M"),
            (103, "binary-tree-zigzag-level-order-traversal", "M"),
            (199, "binary-tree-right-side-view", "M"),
            (1448, "count-good-nodes-in-binary-tree", "M"),
            (98, "validate-binary-search-tree", "M"),
            (230, "kth-smallest-element-in-a-bst", "M"),
            (105, "construct-binary-tree-from-preorder-and-inorder-traversal", "M"),
            (236, "lowest-common-ancestor-of-a-binary-tree", "M"),
            (113, "path-sum-ii", "M"),
            (437, "path-sum-iii", "M"),
            (114, "flatten-binary-tree-to-linked-list", "M"),
            (116, "populating-next-right-pointers-in-each-node", "M"),
            (108, "convert-sorted-array-to-binary-search-tree", "E"),
            (173, "binary-search-tree-iterator", "M"),
            (450, "delete-node-in-a-bst", "M"),
            (662, "maximum-width-of-binary-tree", "M"),
            (863, "all-nodes-distance-k-in-binary-tree", "M"),
            (129, "sum-root-to-leaf-numbers", "M"),
            (337, "house-robber-iii", "M"),
            (1650, "lowest-common-ancestor-of-a-binary-tree-iii", "M"),
            (314, "binary-tree-vertical-order-traversal", "M"),
            (124, "binary-tree-maximum-path-sum", "H"),
            (297, "serialize-and-deserialize-binary-tree", "H"),
            (987, "vertical-order-traversal-of-a-binary-tree", "H"),
        ],
    },
    "trie": {
        "description": "Prefix trees and their applications",
        "problems": [
            (208, "implement-trie-prefix-tree", "M"),
            (211, "design-add-and-search-words-data-structure", "M"),
            (720, "longest-word-in-dictionary", "M"),
            (648, "replace-words", "M"),
            (677, "map-sum-pairs", "M"),
            (1268, "search-suggestions-system", "M"),
            (421, "maximum-xor-of-two-numbers-in-an-array", "M"),
            (212, "word-search-ii", "H"),
            (745, "prefix-and-suffix-search", "H"),
            (472, "concatenated-words", "H"),
            (1032, "stream-of-characters", "H"),
        ],
    },
    "heap": {
        "description": "Priority queues, top-k, scheduling, two-heap median",
        "problems": [
            (703, "kth-largest-element-in-a-stream", "E"),
            (1046, "last-stone-weight", "E"),
            (973, "k-closest-points-to-origin", "M"),
            (215, "kth-largest-element-in-an-array", "M"),
            (347, "top-k-frequent-elements", "M"),
            (692, "top-k-frequent-words", "M"),
            (373, "find-k-pairs-with-smallest-sums", "M"),
            (378, "kth-smallest-element-in-a-sorted-matrix", "M"),
            (621, "task-scheduler", "M"),
            (767, "reorganize-string", "M"),
            (355, "design-twitter", "M"),
            (253, "meeting-rooms-ii", "M"),
            (1834, "single-threaded-cpu", "M"),
            (1642, "furthest-building-you-can-reach", "M"),
            (1353, "maximum-number-of-events-that-can-be-attended", "M"),
            (264, "ugly-number-ii", "M"),
            (295, "find-median-from-data-stream", "H"),
            (23, "merge-k-sorted-lists", "H"),
            (502, "ipo", "H"),
            (632, "smallest-range-covering-elements-from-k-lists", "H"),
            (857, "minimum-cost-to-hire-k-workers", "H"),
            (2402, "meeting-rooms-iii", "H"),
        ],
    },
    "backtracking": {
        "description": "Subsets, permutations, combinations, constraint search",
        "problems": [
            (78, "subsets", "M"),
            (90, "subsets-ii", "M"),
            (77, "combinations", "M"),
            (46, "permutations", "M"),
            (47, "permutations-ii", "M"),
            (39, "combination-sum", "M"),
            (40, "combination-sum-ii", "M"),
            (216, "combination-sum-iii", "M"),
            (17, "letter-combinations-of-a-phone-number", "M"),
            (22, "generate-parentheses", "M"),
            (79, "word-search", "M"),
            (131, "palindrome-partitioning", "M"),
            (93, "restore-ip-addresses", "M"),
            (473, "matchsticks-to-square", "M"),
            (698, "partition-to-k-equal-sum-subsets", "M"),
            (526, "beautiful-arrangement", "M"),
            (51, "n-queens", "H"),
            (52, "n-queens-ii", "H"),
            (37, "sudoku-solver", "H"),
            (140, "word-break-ii", "H"),
            (301, "remove-invalid-parentheses", "H"),
            (282, "expression-add-operators", "H"),
        ],
    },
    # ---------------------------------------------------------------- graphs
    "graphs": {
        "description": "BFS/DFS on grids and adjacency lists, components, bipartite",
        "problems": [
            (1971, "find-if-path-exists-in-graph", "E"),
            (733, "flood-fill", "E"),
            (463, "island-perimeter", "E"),
            (200, "number-of-islands", "M"),
            (695, "max-area-of-island", "M"),
            (133, "clone-graph", "M"),
            (994, "rotting-oranges", "M"),
            (542, "01-matrix", "M"),
            (417, "pacific-atlantic-water-flow", "M"),
            (130, "surrounded-regions", "M"),
            (286, "walls-and-gates", "M"),
            (797, "all-paths-from-source-to-target", "M"),
            (785, "is-graph-bipartite", "M"),
            (547, "number-of-provinces", "M"),
            (1091, "shortest-path-in-binary-matrix", "M"),
            (934, "shortest-bridge", "M"),
            (1020, "number-of-enclaves", "M"),
            (1254, "number-of-closed-islands", "M"),
            (433, "minimum-genetic-mutation", "M"),
            (841, "keys-and-rooms", "M"),
            (1466, "reorder-routes-to-make-all-paths-lead-to-the-city-zero", "M"),
            (2101, "detonate-the-maximum-bombs", "M"),
            (127, "word-ladder", "H"),
            (815, "bus-routes", "H"),
            (1197, "minimum-knight-moves", "M"),
        ],
    },
    "graphs-advanced": {
        "description": "Topological sort, Dijkstra, Bellman-Ford, MST, Tarjan",
        "problems": [
            (207, "course-schedule", "M"),
            (210, "course-schedule-ii", "M"),
            (802, "find-eventual-safe-states", "M"),
            (310, "minimum-height-trees", "M"),
            (1462, "course-schedule-iv", "M"),
            (2115, "find-all-possible-recipes-from-given-supplies", "M"),
            (269, "alien-dictionary", "H"),
            (743, "network-delay-time", "M"),
            (787, "cheapest-flights-within-k-stops", "M"),
            (1631, "path-with-minimum-effort", "M"),
            (1514, "path-with-maximum-probability", "M"),
            (1976, "number-of-ways-to-arrive-at-destination", "M"),
            (1334, "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance", "M"),
            (1584, "min-cost-to-connect-all-points", "M"),
            (778, "swim-in-rising-water", "H"),
            (1368, "minimum-cost-to-make-at-least-one-valid-path-in-a-grid", "H"),
            (332, "reconstruct-itinerary", "H"),
            (1192, "critical-connections-in-a-network", "H"),
            (1489, "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree", "H"),
            (2050, "parallel-courses-iii", "H"),
            (847, "shortest-path-visiting-all-nodes", "H"),
            (2127, "maximum-employees-to-be-invited-to-a-meeting", "H"),
        ],
    },
    "union-find": {
        "description": "Disjoint set union and connectivity queries",
        "problems": [
            (547, "number-of-provinces", "M"),
            (684, "redundant-connection", "M"),
            (1319, "number-of-operations-to-make-network-connected", "M"),
            (990, "satisfiability-of-equality-equations", "M"),
            (721, "accounts-merge", "M"),
            (947, "most-stones-removed-with-same-row-or-column", "M"),
            (1202, "smallest-string-with-swaps", "M"),
            (399, "evaluate-division", "M"),
            (128, "longest-consecutive-sequence", "M"),
            (1061, "lexicographically-smallest-equivalent-string", "M"),
            (2316, "count-unreachable-pairs-of-nodes-in-an-undirected-graph", "M"),
            (959, "regions-cut-by-slashes", "M"),
            (323, "number-of-connected-components-in-an-undirected-graph", "M"),
            (261, "graph-valid-tree", "M"),
            (685, "redundant-connection-ii", "H"),
            (952, "largest-component-size-by-common-factor", "H"),
            (1697, "checking-existence-of-edge-length-limited-paths", "H"),
            (2092, "find-all-people-with-secret", "H"),
            (2421, "number-of-good-paths", "H"),
            (1579, "remove-max-number-of-edges-to-keep-graph-fully-traversable", "H"),
        ],
    },
    # -------------------------------------------------------------------- dp
    "dp-1d": {
        "description": "One-dimensional DP: sequences, knapsack, stock, LIS",
        "problems": [
            (70, "climbing-stairs", "E"),
            (746, "min-cost-climbing-stairs", "E"),
            (118, "pascals-triangle", "E"),
            (198, "house-robber", "M"),
            (213, "house-robber-ii", "M"),
            (740, "delete-and-earn", "M"),
            (55, "jump-game", "M"),
            (45, "jump-game-ii", "M"),
            (152, "maximum-product-subarray", "M"),
            (91, "decode-ways", "M"),
            (322, "coin-change", "M"),
            (518, "coin-change-ii", "M"),
            (279, "perfect-squares", "M"),
            (343, "integer-break", "M"),
            (377, "combination-sum-iv", "M"),
            (139, "word-break", "M"),
            (300, "longest-increasing-subsequence", "M"),
            (673, "number-of-longest-increasing-subsequence", "M"),
            (416, "partition-equal-subset-sum", "M"),
            (494, "target-sum", "M"),
            (1049, "last-stone-weight-ii", "M"),
            (5, "longest-palindromic-substring", "M"),
            (647, "palindromic-substrings", "M"),
            (983, "minimum-cost-for-tickets", "M"),
            (122, "best-time-to-buy-and-sell-stock-ii", "M"),
            (309, "best-time-to-buy-and-sell-stock-with-cooldown", "M"),
            (714, "best-time-to-buy-and-sell-stock-with-transaction-fee", "M"),
            (123, "best-time-to-buy-and-sell-stock-iii", "H"),
            (188, "best-time-to-buy-and-sell-stock-iv", "H"),
            (132, "palindrome-partitioning-ii", "H"),
            (1235, "maximum-profit-in-job-scheduling", "H"),
            (1335, "minimum-difficulty-of-a-job-schedule", "H"),
        ],
    },
    "dp-2d": {
        "description": "Grid DP, two-sequence DP, interval DP, game DP",
        "problems": [
            (62, "unique-paths", "M"),
            (63, "unique-paths-ii", "M"),
            (64, "minimum-path-sum", "M"),
            (120, "triangle", "M"),
            (931, "minimum-falling-path-sum", "M"),
            (221, "maximal-square", "M"),
            (1143, "longest-common-subsequence", "M"),
            (1035, "uncrossed-lines", "M"),
            (718, "maximum-length-of-repeated-subarray", "M"),
            (583, "delete-operation-for-two-strings", "M"),
            (516, "longest-palindromic-subsequence", "M"),
            (97, "interleaving-string", "M"),
            (474, "ones-and-zeroes", "M"),
            (1155, "number-of-dice-rolls-with-target-sum", "M"),
            (877, "stone-game", "M"),
            (486, "predict-the-winner", "M"),
            (1140, "stone-game-ii", "M"),
            (375, "guess-number-higher-or-lower-ii", "M"),
            (1770, "maximum-score-from-performing-multiplication-operations", "H"),
            (329, "longest-increasing-path-in-a-matrix", "H"),
            (72, "edit-distance", "M"),
            (115, "distinct-subsequences", "H"),
            (174, "dungeon-game", "H"),
            (312, "burst-balloons", "H"),
            (1547, "minimum-cost-to-cut-a-stick", "H"),
            (1000, "minimum-cost-to-merge-stones", "H"),
            (10, "regular-expression-matching", "H"),
            (44, "wildcard-matching", "H"),
            (1463, "cherry-pickup-ii", "H"),
            (887, "super-egg-drop", "H"),
        ],
    },
    "greedy": {
        "description": "Exchange arguments, scheduling, local-optimal choices",
        "problems": [
            (455, "assign-cookies", "E"),
            (860, "lemonade-change", "E"),
            (1005, "maximize-sum-of-array-after-k-negations", "E"),
            (53, "maximum-subarray", "M"),
            (55, "jump-game", "M"),
            (45, "jump-game-ii", "M"),
            (134, "gas-station", "M"),
            (846, "hand-of-straights", "M"),
            (1899, "merge-triplets-to-form-target-triplet", "M"),
            (763, "partition-labels", "M"),
            (678, "valid-parenthesis-string", "M"),
            (1029, "two-city-scheduling", "M"),
            (881, "boats-to-save-people", "M"),
            (452, "minimum-number-of-arrows-to-burst-balloons", "M"),
            (435, "non-overlapping-intervals", "M"),
            (406, "queue-reconstruction-by-height", "M"),
            (621, "task-scheduler", "M"),
            (179, "largest-number", "M"),
            (738, "monotone-increasing-digits", "M"),
            (1024, "video-stitching", "M"),
            (1405, "longest-happy-string", "M"),
            (135, "candy", "H"),
            (1326, "minimum-number-of-taps-to-open-to-water-a-garden", "H"),
            (330, "patching-array", "H"),
            (2136, "earliest-possible-day-of-full-bloom", "H"),
        ],
    },
    "intervals": {
        "description": "Merging, scheduling, sweep line, calendars",
        "problems": [
            (228, "summary-ranges", "E"),
            (252, "meeting-rooms", "E"),
            (56, "merge-intervals", "M"),
            (57, "insert-interval", "M"),
            (435, "non-overlapping-intervals", "M"),
            (253, "meeting-rooms-ii", "M"),
            (986, "interval-list-intersections", "M"),
            (1288, "remove-covered-intervals", "M"),
            (452, "minimum-number-of-arrows-to-burst-balloons", "M"),
            (729, "my-calendar-i", "M"),
            (731, "my-calendar-ii", "M"),
            (1094, "car-pooling", "M"),
            (636, "exclusive-time-of-functions", "M"),
            (1353, "maximum-number-of-events-that-can-be-attended", "M"),
            (2406, "divide-intervals-into-minimum-number-of-groups", "M"),
            (1851, "minimum-interval-to-include-each-query", "H"),
            (732, "my-calendar-iii", "H"),
            (218, "the-skyline-problem", "H"),
            (352, "data-stream-as-disjoint-intervals", "H"),
            (2402, "meeting-rooms-iii", "H"),
        ],
    },
    # --------------------------------------------------------------- strings
    "strings": {
        "description": "Parsing, palindromes, pattern matching, string building",
        "problems": [
            (14, "longest-common-prefix", "E"),
            (28, "find-the-index-of-the-first-occurrence-in-a-string", "E"),
            (58, "length-of-last-word", "E"),
            (205, "isomorphic-strings", "E"),
            (290, "word-pattern", "E"),
            (383, "ransom-note", "E"),
            (387, "first-unique-character-in-a-string", "E"),
            (392, "is-subsequence", "E"),
            (409, "longest-palindrome", "E"),
            (415, "add-strings", "E"),
            (844, "backspace-string-compare", "E"),
            (953, "verifying-an-alien-dictionary", "E"),
            (1768, "merge-strings-alternately", "E"),
            (443, "string-compression", "M"),
            (151, "reverse-words-in-a-string", "M"),
            (6, "zigzag-conversion", "M"),
            (8, "string-to-integer-atoi", "M"),
            (12, "integer-to-roman", "M"),
            (43, "multiply-strings", "M"),
            (165, "compare-version-numbers", "M"),
            (5, "longest-palindromic-substring", "M"),
            (1249, "minimum-remove-to-make-valid-parentheses", "M"),
            (921, "minimum-add-to-make-parentheses-valid", "M"),
            (833, "find-and-replace-in-string", "M"),
            (1041, "robot-bounded-in-circle", "M"),
            (187, "repeated-dna-sequences", "M"),
            (468, "validate-ip-address", "M"),
            (68, "text-justification", "H"),
            (273, "integer-to-english-words", "H"),
            (214, "shortest-palindrome", "H"),
            (336, "palindrome-pairs", "H"),
            (65, "valid-number", "H"),
        ],
    },
    "math-geometry": {
        "description": "Number theory, simulation, matrix rotation, randomness",
        "problems": [
            (9, "palindrome-number", "E"),
            (66, "plus-one", "E"),
            (202, "happy-number", "E"),
            (13, "roman-to-integer", "E"),
            (171, "excel-sheet-column-number", "E"),
            (168, "excel-sheet-column-title", "E"),
            (172, "factorial-trailing-zeroes", "M"),
            (204, "count-primes", "M"),
            (367, "valid-perfect-square", "E"),
            (1071, "greatest-common-divisor-of-strings", "E"),
            (7, "reverse-integer", "M"),
            (50, "powx-n", "M"),
            (29, "divide-two-integers", "M"),
            (48, "rotate-image", "M"),
            (54, "spiral-matrix", "M"),
            (59, "spiral-matrix-ii", "M"),
            (73, "set-matrix-zeroes", "M"),
            (289, "game-of-life", "M"),
            (166, "fraction-to-recurring-decimal", "M"),
            (365, "water-and-jug-problem", "M"),
            (470, "implement-rand10-using-rand7", "M"),
            (478, "generate-random-point-in-a-circle", "M"),
            (528, "random-pick-with-weight", "M"),
            (384, "shuffle-an-array", "M"),
            (836, "rectangle-overlap", "E"),
            (223, "rectangle-area", "M"),
            (593, "valid-square", "M"),
            (2013, "detect-squares", "M"),
            (149, "max-points-on-a-line", "H"),
            (60, "permutation-sequence", "H"),
            (233, "number-of-digit-one", "H"),
        ],
    },
    "bit-manipulation": {
        "description": "XOR tricks, bit counting, masks",
        "problems": [
            (136, "single-number", "E"),
            (191, "number-of-1-bits", "E"),
            (338, "counting-bits", "E"),
            (190, "reverse-bits", "E"),
            (268, "missing-number", "E"),
            (231, "power-of-two", "E"),
            (342, "power-of-four", "E"),
            (389, "find-the-difference", "E"),
            (461, "hamming-distance", "E"),
            (476, "number-complement", "E"),
            (1009, "complement-of-base-10-integer", "E"),
            (371, "sum-of-two-integers", "M"),
            (137, "single-number-ii", "M"),
            (260, "single-number-iii", "M"),
            (201, "bitwise-and-of-numbers-range", "M"),
            (477, "total-hamming-distance", "M"),
            (421, "maximum-xor-of-two-numbers-in-an-array", "M"),
            (1318, "minimum-flips-to-make-a-or-b-equal-to-c", "M"),
            (1310, "xor-queries-of-a-subarray", "M"),
            (1442, "count-triplets-that-can-form-two-arrays-of-equal-xor", "M"),
            (1239, "maximum-length-of-a-concatenated-string-with-unique-characters", "M"),
            (393, "utf-8-validation", "M"),
            (898, "bitwise-ors-of-subarrays", "M"),
            (1611, "minimum-one-bit-operations-to-make-integers-zero", "H"),
        ],
    },
    # ---------------------------------------------------------------- design
    "design": {
        "description": "Data-structure design and OOP-style system questions",
        "problems": [
            (705, "design-hashset", "E"),
            (706, "design-hashmap", "E"),
            (933, "number-of-recent-calls", "E"),
            (1603, "design-parking-system", "E"),
            (155, "min-stack", "M"),
            (232, "implement-queue-using-stacks", "E"),
            (225, "implement-stack-using-queues", "E"),
            (622, "design-circular-queue", "M"),
            (641, "design-circular-deque", "M"),
            (707, "design-linked-list", "M"),
            (146, "lru-cache", "M"),
            (208, "implement-trie-prefix-tree", "M"),
            (211, "design-add-and-search-words-data-structure", "M"),
            (380, "insert-delete-getrandom-o1", "M"),
            (381, "insert-delete-getrandom-o1-duplicates-allowed", "H"),
            (341, "flatten-nested-list-iterator", "M"),
            (173, "binary-search-tree-iterator", "M"),
            (355, "design-twitter", "M"),
            (981, "time-based-key-value-store", "M"),
            (1146, "snapshot-array", "M"),
            (1396, "design-underground-system", "M"),
            (1472, "design-browser-history", "M"),
            (2034, "stock-price-fluctuation", "M"),
            (2353, "design-a-food-rating-system", "M"),
            (1352, "product-of-the-last-k-numbers", "M"),
            (729, "my-calendar-i", "M"),
            (901, "online-stock-span", "M"),
            (895, "maximum-frequency-stack", "H"),
            (432, "all-oone-data-structure", "H"),
            (460, "lfu-cache", "H"),
            (295, "find-median-from-data-stream", "H"),
            (297, "serialize-and-deserialize-binary-tree", "H"),
            (715, "range-module", "H"),
            (1206, "design-skiplist", "H"),
            (2296, "design-a-text-editor", "H"),
            (346, "moving-average-from-data-stream", "E"),
            (359, "logger-rate-limiter", "E"),
            (362, "design-hit-counter", "M"),
            (348, "design-tic-tac-toe", "M"),
            (588, "design-in-memory-file-system", "H"),
        ],
    },
    "advanced-structures": {
        "description": "Monotonic deque, segment tree / BIT, ordered sets",
        "problems": [
            (239, "sliding-window-maximum", "H"),
            (1438, "longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit", "M"),
            (1696, "jump-game-vi", "M"),
            (1425, "constrained-subsequence-sum", "H"),
            (862, "shortest-subarray-with-sum-at-least-k", "H"),
            (962, "maximum-width-ramp", "M"),
            (2104, "sum-of-subarray-ranges", "M"),
            (1856, "maximum-subarray-min-product", "M"),
            (307, "range-sum-query-mutable", "M"),
            (1395, "count-number-of-teams", "M"),
            (315, "count-of-smaller-numbers-after-self", "H"),
            (493, "reverse-pairs", "H"),
            (327, "count-of-range-sum", "H"),
            (1649, "create-sorted-array-through-instructions", "H"),
            (2407, "longest-increasing-subsequence-ii", "H"),
            (699, "falling-squares", "H"),
            (218, "the-skyline-problem", "H"),
            (1157, "online-majority-element-in-subarray", "H"),
            (2276, "count-integers-in-intervals", "H"),
            (480, "sliding-window-median", "H"),
        ],
    },
    # ------------------------------------------------------------- meta sets
    "blind75": {
        "description": "The classic Blind 75 interview list",
        "problems": [
            (1, "two-sum", "E"),
            (121, "best-time-to-buy-and-sell-stock", "E"),
            (217, "contains-duplicate", "E"),
            (238, "product-of-array-except-self", "M"),
            (53, "maximum-subarray", "M"),
            (152, "maximum-product-subarray", "M"),
            (153, "find-minimum-in-rotated-sorted-array", "M"),
            (33, "search-in-rotated-sorted-array", "M"),
            (15, "3sum", "M"),
            (11, "container-with-most-water", "M"),
            (371, "sum-of-two-integers", "M"),
            (191, "number-of-1-bits", "E"),
            (338, "counting-bits", "E"),
            (268, "missing-number", "E"),
            (190, "reverse-bits", "E"),
            (70, "climbing-stairs", "E"),
            (322, "coin-change", "M"),
            (300, "longest-increasing-subsequence", "M"),
            (1143, "longest-common-subsequence", "M"),
            (139, "word-break", "M"),
            (377, "combination-sum-iv", "M"),
            (198, "house-robber", "M"),
            (213, "house-robber-ii", "M"),
            (91, "decode-ways", "M"),
            (62, "unique-paths", "M"),
            (55, "jump-game", "M"),
            (133, "clone-graph", "M"),
            (207, "course-schedule", "M"),
            (417, "pacific-atlantic-water-flow", "M"),
            (200, "number-of-islands", "M"),
            (128, "longest-consecutive-sequence", "M"),
            (269, "alien-dictionary", "H"),
            (261, "graph-valid-tree", "M"),
            (323, "number-of-connected-components-in-an-undirected-graph", "M"),
            (57, "insert-interval", "M"),
            (56, "merge-intervals", "M"),
            (435, "non-overlapping-intervals", "M"),
            (252, "meeting-rooms", "E"),
            (253, "meeting-rooms-ii", "M"),
            (206, "reverse-linked-list", "E"),
            (141, "linked-list-cycle", "E"),
            (21, "merge-two-sorted-lists", "E"),
            (23, "merge-k-sorted-lists", "H"),
            (19, "remove-nth-node-from-end-of-list", "M"),
            (143, "reorder-list", "M"),
            (73, "set-matrix-zeroes", "M"),
            (54, "spiral-matrix", "M"),
            (48, "rotate-image", "M"),
            (79, "word-search", "M"),
            (3, "longest-substring-without-repeating-characters", "M"),
            (424, "longest-repeating-character-replacement", "M"),
            (76, "minimum-window-substring", "H"),
            (242, "valid-anagram", "E"),
            (49, "group-anagrams", "M"),
            (20, "valid-parentheses", "E"),
            (125, "valid-palindrome", "E"),
            (5, "longest-palindromic-substring", "M"),
            (647, "palindromic-substrings", "M"),
            (271, "encode-and-decode-strings", "M"),
            (104, "maximum-depth-of-binary-tree", "E"),
            (100, "same-tree", "E"),
            (226, "invert-binary-tree", "E"),
            (124, "binary-tree-maximum-path-sum", "H"),
            (102, "binary-tree-level-order-traversal", "M"),
            (297, "serialize-and-deserialize-binary-tree", "H"),
            (572, "subtree-of-another-tree", "E"),
            (105, "construct-binary-tree-from-preorder-and-inorder-traversal", "M"),
            (98, "validate-binary-search-tree", "M"),
            (230, "kth-smallest-element-in-a-bst", "M"),
            (235, "lowest-common-ancestor-of-a-binary-search-tree", "M"),
            (208, "implement-trie-prefix-tree", "M"),
            (211, "design-add-and-search-words-data-structure", "M"),
            (212, "word-search-ii", "H"),
            (347, "top-k-frequent-elements", "M"),
            (295, "find-median-from-data-stream", "H"),
        ],
    },
    "big-tech": {
        "description": "Most frequently reported in Google/Meta/Amazon/Microsoft/Apple loops",
        "problems": [
            (1, "two-sum", "E"),
            (20, "valid-parentheses", "E"),
            (21, "merge-two-sorted-lists", "E"),
            (121, "best-time-to-buy-and-sell-stock", "E"),
            (125, "valid-palindrome", "E"),
            (206, "reverse-linked-list", "E"),
            (680, "valid-palindrome-ii", "E"),
            (953, "verifying-an-alien-dictionary", "E"),
            (1762, "buildings-with-an-ocean-view", "M"),
            (1570, "dot-product-of-two-sparse-vectors", "M"),
            (2, "add-two-numbers", "M"),
            (3, "longest-substring-without-repeating-characters", "M"),
            (5, "longest-palindromic-substring", "M"),
            (11, "container-with-most-water", "M"),
            (15, "3sum", "M"),
            (17, "letter-combinations-of-a-phone-number", "M"),
            (22, "generate-parentheses", "M"),
            (33, "search-in-rotated-sorted-array", "M"),
            (36, "valid-sudoku", "M"),
            (39, "combination-sum", "M"),
            (46, "permutations", "M"),
            (48, "rotate-image", "M"),
            (49, "group-anagrams", "M"),
            (50, "powx-n", "M"),
            (53, "maximum-subarray", "M"),
            (54, "spiral-matrix", "M"),
            (56, "merge-intervals", "M"),
            (62, "unique-paths", "M"),
            (71, "simplify-path", "M"),
            (78, "subsets", "M"),
            (79, "word-search", "M"),
            (91, "decode-ways", "M"),
            (98, "validate-binary-search-tree", "M"),
            (102, "binary-tree-level-order-traversal", "M"),
            (128, "longest-consecutive-sequence", "M"),
            (133, "clone-graph", "M"),
            (138, "copy-list-with-random-pointer", "M"),
            (139, "word-break", "M"),
            (143, "reorder-list", "M"),
            (146, "lru-cache", "M"),
            (152, "maximum-product-subarray", "M"),
            (155, "min-stack", "M"),
            (162, "find-peak-element", "M"),
            (199, "binary-tree-right-side-view", "M"),
            (200, "number-of-islands", "M"),
            (207, "course-schedule", "M"),
            (208, "implement-trie-prefix-tree", "M"),
            (215, "kth-largest-element-in-an-array", "M"),
            (227, "basic-calculator-ii", "M"),
            (236, "lowest-common-ancestor-of-a-binary-tree", "M"),
            (238, "product-of-array-except-self", "M"),
            (253, "meeting-rooms-ii", "M"),
            (322, "coin-change", "M"),
            (347, "top-k-frequent-elements", "M"),
            (380, "insert-delete-getrandom-o1", "M"),
            (394, "decode-string", "M"),
            (399, "evaluate-division", "M"),
            (416, "partition-equal-subset-sum", "M"),
            (528, "random-pick-with-weight", "M"),
            (560, "subarray-sum-equals-k", "M"),
            (621, "task-scheduler", "M"),
            (636, "exclusive-time-of-functions", "M"),
            (721, "accounts-merge", "M"),
            (739, "daily-temperatures", "M"),
            (763, "partition-labels", "M"),
            (767, "reorganize-string", "M"),
            (863, "all-nodes-distance-k-in-binary-tree", "M"),
            (875, "koko-eating-bananas", "M"),
            (973, "k-closest-points-to-origin", "M"),
            (981, "time-based-key-value-store", "M"),
            (994, "rotting-oranges", "M"),
            (1091, "shortest-path-in-binary-matrix", "M"),
            (1249, "minimum-remove-to-make-valid-parentheses", "M"),
            (1268, "search-suggestions-system", "M"),
            (1650, "lowest-common-ancestor-of-a-binary-tree-iii", "M"),
            (314, "binary-tree-vertical-order-traversal", "M"),
            (4, "median-of-two-sorted-arrays", "H"),
            (23, "merge-k-sorted-lists", "H"),
            (25, "reverse-nodes-in-k-group", "H"),
            (42, "trapping-rain-water", "H"),
            (76, "minimum-window-substring", "H"),
            (84, "largest-rectangle-in-histogram", "H"),
            (124, "binary-tree-maximum-path-sum", "H"),
            (127, "word-ladder", "H"),
            (212, "word-search-ii", "H"),
            (224, "basic-calculator", "H"),
            (239, "sliding-window-maximum", "H"),
            (269, "alien-dictionary", "H"),
            (295, "find-median-from-data-stream", "H"),
            (297, "serialize-and-deserialize-binary-tree", "H"),
            (329, "longest-increasing-path-in-a-matrix", "H"),
            (332, "reconstruct-itinerary", "H"),
            (460, "lfu-cache", "H"),
            (987, "vertical-order-traversal-of-a-binary-tree", "H"),
            (1235, "maximum-profit-in-job-scheduling", "H"),
        ],
    },
}


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def _normalize_problem(entry) -> tuple[int | None, str | None, str | None]:
    """Turn a built-in tuple or a user-supplied slug/ID into (id, slug, diff)."""
    if isinstance(entry, (list, tuple)):
        pid = int(entry[0]) if len(entry) > 0 and entry[0] is not None else None
        slug = entry[1] if len(entry) > 1 else None
        diff = entry[2] if len(entry) > 2 else None
        if diff:
            diff = str(diff)[0].upper()
            if diff not in DIFF_WEIGHT:
                diff = None
        return pid, slug, diff
    if isinstance(entry, int) or (isinstance(entry, str) and entry.isdigit()):
        return int(entry), None, None
    if isinstance(entry, str):
        return None, entry.strip(), None
    return None, None, None


def load_user_sets() -> dict[str, dict]:
    if not USER_SETS_FILE.exists():
        return {}
    try:
        with open(USER_SETS_FILE, "r") as f:
            raw = json.load(f)
    except Exception:
        return {}
    if not isinstance(raw, dict):
        return {}

    result = {}
    for name, body in raw.items():
        if isinstance(body, list):
            body = {"problems": body}
        if not isinstance(body, dict):
            continue
        problems = [_normalize_problem(p) for p in body.get("problems", [])]
        problems = [p for p in problems if p[0] is not None or p[1]]
        result[str(name)] = {
            "description": body.get("description", "User-defined set"),
            "problems": problems,
            "user": True,
        }
    return result


def get_all_sets() -> dict[str, dict]:
    """Built-in sets merged with user sets (user sets override by name)."""
    sets = {}
    for name, body in BUILTIN_SETS.items():
        sets[name] = {
            "description": body["description"],
            "problems": [_normalize_problem(p) for p in body["problems"]],
            "user": False,
        }
    sets.update(load_user_sets())
    return sets


def find_set(name: str, sets: dict[str, dict] | None = None) -> tuple[str, dict] | None:
    """Look a set up by exact name, then by unique prefix / substring."""
    sets = sets if sets is not None else get_all_sets()
    key = name.strip().lower()
    if key in sets:
        return key, sets[key]
    prefix = [k for k in sets if k.startswith(key)]
    if len(prefix) == 1:
        return prefix[0], sets[prefix[0]]
    contains = [k for k in sets if key in k]
    if len(contains) == 1:
        return contains[0], sets[contains[0]]
    return None


def level_label(pct: float) -> tuple[str, str]:
    """Map a 0-100 percentage to (label, rich color)."""
    if pct >= 100:
        return "Mastered", "bold green"
    if pct >= 75:
        return "Strong", "green"
    if pct >= 50:
        return "Solid", "yellow"
    if pct >= 25:
        return "Learning", "magenta"
    if pct > 0:
        return "Started", "red"
    return "Untouched", "dim"
